[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<../chronobell.ino> +<./>
lib_deps =
    MD_MAX72xx
    NTPClient
board_build.extra_flags = -Isrc -I.
build_flags = -fno-exceptions -fno-rtti
