[common]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<./>
lib_deps =
    MD_MAX72xx
    NTPClient
board_build.extra_flags = -Isrc -I.
build_flags = -fno-exceptions -fno-rtti

[env:esp32dev]
extends = common

[env:esp32dev-ota]
extends = common
upload_protocol = espota
upload_port = chronobell.local
upload_flags =
    --auth=chronobell

